# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import draw_react_icons_pb2 as draw__react__icons__pb2


class IconEstimatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryImage = channel.unary_unary(
                '/drawreacticons.IconEstimator/QueryImage',
                request_serializer=draw__react__icons__pb2.ImageQuery.SerializeToString,
                response_deserializer=draw__react__icons__pb2.Icons.FromString,
                )
        self.GetCollectionInfo = channel.unary_unary(
                '/drawreacticons.IconEstimator/GetCollectionInfo',
                request_serializer=draw__react__icons__pb2.Empty.SerializeToString,
                response_deserializer=draw__react__icons__pb2.Collections.FromString,
                )


class IconEstimatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectionInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IconEstimatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryImage': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryImage,
                    request_deserializer=draw__react__icons__pb2.ImageQuery.FromString,
                    response_serializer=draw__react__icons__pb2.Icons.SerializeToString,
            ),
            'GetCollectionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectionInfo,
                    request_deserializer=draw__react__icons__pb2.Empty.FromString,
                    response_serializer=draw__react__icons__pb2.Collections.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drawreacticons.IconEstimator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IconEstimator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/drawreacticons.IconEstimator/QueryImage',
            draw__react__icons__pb2.ImageQuery.SerializeToString,
            draw__react__icons__pb2.Icons.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCollectionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/drawreacticons.IconEstimator/GetCollectionInfo',
            draw__react__icons__pb2.Empty.SerializeToString,
            draw__react__icons__pb2.Collections.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
