# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: draw_react_icons.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x64raw_react_icons.proto\x12\x0e\x64rawreacticons\"f\n\nImageQuery\x12\x13\n\x0b\x62\x61se64image\x18\x01 \x01(\t\x12\x16\n\x0e\x63ollectionName\x18\x02 \x01(\t\x12\x13\n\x0binvertImage\x18\x03 \x01(\x08\x12\x16\n\x0enormalizeImage\x18\x04 \x01(\x08\"\x07\n\x05\x45mpty\":\n\x04Icon\x12\x0e\n\x06iconID\x18\x01 \x01(\t\x12\x10\n\x08parentID\x18\x02 \x01(\t\x12\x10\n\x08iconName\x18\x03 \x01(\t\",\n\x05Icons\x12#\n\x05icons\x18\x01 \x03(\x0b\x32\x14.drawreacticons.Icon\">\n\x0b\x43ollections\x12/\n\x0b\x63ollections\x18\x01 \x03(\x0b\x32\x1a.drawreacticons.Collection\"E\n\nCollection\x12\x10\n\x08\x65mbedder\x18\x01 \x01(\t\x12\r\n\x05index\x18\x02 \x01(\t\x12\x16\n\x0e\x63ollectionName\x18\x03 \x01(\t2\x99\x01\n\rIconEstimator\x12?\n\nQueryImage\x12\x1a.drawreacticons.ImageQuery\x1a\x15.drawreacticons.Icons\x12G\n\x11GetCollectionInfo\x12\x15.drawreacticons.Empty\x1a\x1b.drawreacticons.Collectionsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'draw_react_icons_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_IMAGEQUERY']._serialized_start=42
  _globals['_IMAGEQUERY']._serialized_end=144
  _globals['_EMPTY']._serialized_start=146
  _globals['_EMPTY']._serialized_end=153
  _globals['_ICON']._serialized_start=155
  _globals['_ICON']._serialized_end=213
  _globals['_ICONS']._serialized_start=215
  _globals['_ICONS']._serialized_end=259
  _globals['_COLLECTIONS']._serialized_start=261
  _globals['_COLLECTIONS']._serialized_end=323
  _globals['_COLLECTION']._serialized_start=325
  _globals['_COLLECTION']._serialized_end=394
  _globals['_ICONESTIMATOR']._serialized_start=397
  _globals['_ICONESTIMATOR']._serialized_end=550
# @@protoc_insertion_point(module_scope)
