name: Docker Build and Push

on:
  push:
    branches:
      - "main"
    paths:
      - "py-script/**"
  

env:
  TAGS: ${{ github.sha }}

  # Please fill this
  DOCKER_REPOSITORY: kaenova/draw-react-icons-api

jobs:
  DockerImage:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./py-script
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: DockerHub Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build Docker Image
        run: docker build --tag "$DOCKER_REPOSITORY:$TAGS" --tag "$DOCKER_REPOSITORY:latest" .

      - name: Dockerhub Push
        run: docker push $DOCKER_REPOSITORY --all-tags

      - name: Portainer Hook Update
        run: curl -X POST ${{ secrets.BACKEND_UPDATE_WEBHOOK_URL }}